### ISSUE TITLE
ssh和ping都没问题，ss服务死活连不上

### ISSUE THREAD

**Issue by Upapanow** [lanlandezei/shadowsocks-libev#1]
`Aug 25 10:20:07 instance-20210825-1957 systemd[1]: Started Service for snap application shadowsocks-libev.ss-server-daemon.
Aug 25 10:20:07 instance-20210825-1957 shadowsocks-libev.ss-server-daemon[27871]:  2021-08-25 10:20:07 ERROR: Invalid config path.
Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Main process exited, code=exited, status=255/EXCEPT>
Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Failed with result 'exit-code'.`

Oracle Cloud Ubuntu20.04 
配置照搬[https://gfw.report/blog/ss_tutorial/zh/](url) 除了密码
本身人在墙外，应该不存封IP的问题
想问一下这是什么原因？

**Comment by lanlandezei** [comment]
重新执行一下脚本看看

**Comment by lanlandezei** [comment]
> `Aug 25 10:20:07 instance-20210825-1957 systemd[1]: Started Service for snap application shadowsocks-libev.ss-server-daemon. Aug 25 10:20:07 instance-20210825-1957 shadowsocks-libev.ss-server-daemon[27871]: 2021-08-25 10:20:07 ERROR: Invalid config path. Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Main process exited, code=exited, status=255/EXCEPT> Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Failed with result 'exit-code'.`
> 
> Oracle Cloud Ubuntu20.04
> 配置迁移[https://gfw.report/blog/ss_tutorial/zh/](url)除了密码制造
> 人在墙外，应该不封IP 的问题
> 看看一下这是什么原因？

**Comment by lanlandezei** [comment]
> `Aug 25 10:20:07 instance-20210825-1957 systemd[1]: Started Service for snap application shadowsocks-libev.ss-server-daemon. Aug 25 10:20:07 instance-20210825-1957 shadowsocks-libev.ss-server-daemon[27871]: 2021-08-25 10:20:07 ERROR: Invalid config path. Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Main process exited, code=exited, status=255/EXCEPT> Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Failed with result 'exit-code'.`
> 
> Oracle Cloud Ubuntu20.04
> 配置迁移[https://gfw.report/blog/ss_tutorial/zh/](url)除了密码制造
> 人在墙外，应该不封IP 的问题
> 看看一下这是什么原因？

**Comment by lanlandezei** [comment]
> `Aug 25 10:20:07 instance-20210825-1957 systemd[1]: Started Service for snap application shadowsocks-libev.ss-server-daemon. Aug 25 10:20:07 instance-20210825-1957 shadowsocks-libev.ss-server-daemon[27871]: 2021-08-25 10:20:07 ERROR: Invalid config path. Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Main process exited, code=exited, status=255/EXCEPT> Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Failed with result 'exit-code'.`
> 
> Oracle Cloud Ubuntu20.04
> 配置迁移[https://gfw.report/blog/ss_tutorial/zh/](url)除了密码制造
> 人在墙外，应该不封IP 的问题
> 看看一下这是什么原因？

https://t.me/lanlandezei  或者你加一下我电报

**Comment by Upapanow** [comment]
> > `Aug 25 10:20:07 instance-20210825-1957 systemd[1]: Started Service for snap application shadowsocks-libev.ss-server-daemon. Aug 25 10:20:07 instance-20210825-1957 shadowsocks-libev.ss-server-daemon[27871]: 2021-08-25 10:20:07 ERROR: Invalid config path. Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Main process exited, code=exited, status=255/EXCEPT> Aug 25 10:20:07 instance-20210825-1957 systemd[1]: snap.shadowsocks-libev.ss-server-daemon.service: Failed with result 'exit-code'.`
> > Oracle Cloud Ubuntu20.04
> > 配置迁移[https://gfw.report/blog/ss_tutorial/zh/](url)除了密码制造
> > 人在墙外，应该不封IP 的问题
> > 看看一下这是什么原因？
> 
> https://t.me/lanlandezei 或者你加一下我电报

已经发送了消息。
